version: "3"

services:
  mongodb:
    image: "mongo:7.0.1"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "user"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - mongoExample

  python:
    build: .
    depends_on:
      - mongodb
    networks:
      - mongoExample

networks:
  mongoExample:
